[package]
name = "client"
version = "0.1.0"
authors = ["Flying-Toast"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
	"Window",
]
