version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/common"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/client"
    schedule:
      interval: "daily"
