[package]
name = "backend"
version = "0.1.0"
authors = ["Flying-Toast"]
edition = "2018"

[dependencies]
common = { path = "../common" }
tokio-tungstenite = "0.11"
tokio = "0.2"
futures-util = "0.3"
strum = "0.19"
strum_macros = "0.19"
flume = "0.7"
rand = "0.7"
