[package]
name = "backend"
version = "0.1.0"
authors = ["Flying-Toast"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
common = { path = "../common" }
tokio-tungstenite = "0.11"
tokio = "1.3"
futures-util = "0.3"
flume = "0.9"
rand = "0.7"
lz4-compress = "0.1"
