[package]
name = "backend"
version = "0.1.0"
authors = ["Flying-Toast"]
edition = "2018"

[dependencies]
tokio-tungstenite = "0.10"
tokio = "0.2"
futures-util = "0.3"
strum = "0.18"
strum_macros = "0.18"
flume = "0.7"
rand = "0.7"
